# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M/jWKPpZCeZfra0OalG8daBnCKLcUPp14tOA18ne6SCfQwPH8OGE+kRvh3JoWEQjmIqBSqOdJLCgY1L0404p1k5HTm0C4YvxPp5Yt+nQKU5/uWj+GO9PwgDsjrfKtQoADMFTxmBKcu4kFD6P1Af6QAzz7aRg32q/ab3Cb5L0LlWELiQs1AdNDrgIfVF3nEs6RCBFCI6UkVU7dgC+I0PQW4hjDp3CrElLAYEGyn8ucGm/mUDWUD0btQUGawuQ+gRRQT0N51VFCOMUxAj3JKDaGTVlo+498GKxpq22rVtKHa6OcGD8CmNZ8NGr07DEEubQyNta6ITSgKhTn/pIFOjBfeDC5Wj7+b2ub9w5EbYOvsHlvfjf5FdeWhzMoOwyd8jUmuKjltQKvt/c9VV+J7J9ZdYtzUsTCkriXRDzkujZk75RHlzypYjtz5Xdq3NfIWeXUZI/nrC6L2SwyESz78+Zxaw8v+KJd6kUHW/EpPJrJbiwabRfy7F/ul16++XqDFXA+OjfExKv/0hHk6p+jqdSuD4D0L6xAh4wKpaLD1w8EHee9ElIIlqN+ouWUIybjYCpw9hRA6xlU75ksWtLgAAbsvgFrckyrgeS+4451UuRLcwca3vu/z5pP56TwW+4fERe8NpoYAAI55zMjionsilfDgVomML3cw44NADITWGfjfM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
