travis:
  secure:
    BINSTAR_TOKEN: M/jWKPpZCeZfra0OalG8daBnCKLcUPp14tOA18ne6SCfQwPH8OGE+kRvh3JoWEQjmIqBSqOdJLCgY1L0404p1k5HTm0C4YvxPp5Yt+nQKU5/uWj+GO9PwgDsjrfKtQoADMFTxmBKcu4kFD6P1Af6QAzz7aRg32q/ab3Cb5L0LlWELiQs1AdNDrgIfVF3nEs6RCBFCI6UkVU7dgC+I0PQW4hjDp3CrElLAYEGyn8ucGm/mUDWUD0btQUGawuQ+gRRQT0N51VFCOMUxAj3JKDaGTVlo+498GKxpq22rVtKHa6OcGD8CmNZ8NGr07DEEubQyNta6ITSgKhTn/pIFOjBfeDC5Wj7+b2ub9w5EbYOvsHlvfjf5FdeWhzMoOwyd8jUmuKjltQKvt/c9VV+J7J9ZdYtzUsTCkriXRDzkujZk75RHlzypYjtz5Xdq3NfIWeXUZI/nrC6L2SwyESz78+Zxaw8v+KJd6kUHW/EpPJrJbiwabRfy7F/ul16++XqDFXA+OjfExKv/0hHk6p+jqdSuD4D0L6xAh4wKpaLD1w8EHee9ElIIlqN+ouWUIybjYCpw9hRA6xlU75ksWtLgAAbsvgFrckyrgeS+4451UuRLcwca3vu/z5pP56TwW+4fERe8NpoYAAI55zMjionsilfDgVomML3cw44NADITWGfjfM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
